### ISSUE TITLE
Cannot switch to old mode now.

### ISSUE THREAD

**Issue by 18601673727** [assaf/node-passbook#32]
`npm install passbook --save`
```
passbook@2.1.0 node_modules/passbook
└── cli@0.6.5 (exit@0.1.2, glob@3.2.11)
```
```
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:730:11)
    at IncomingMessage.Readable.resume (_stream_readable.js:715:3)
    at ClientRequest.<anonymous> (/Users/dev/repo/pass/node_modules/passbook/lib/pass.js:299:20)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:527:27)
```

**Comment by 18601673727** [comment]
update node to v0.12 solved this issue.

**Comment by mjwheatley** [comment]
I am receiving this error running node v.0.12.4 and passbook@2.1.1

**Comment by mjwheatley** [comment]
I was able to resolve the error by commenting out line 32 of /lib/pass.js
301  response.pipe(file)
302  //response.resume();
