### ISSUE TITLE
Error on signManifest call

### ISSUE THREAD

**Issue by ipryshlyak** [assaf/node-passbook#40]
i'm getting this error when openssl child proccess is trying to write

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at Socket._writeGeneric (net.js:690:26)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at signManifest (...\node_modules\passbook\lib\pass.js:360:14)
    at Pass.signZip (...\node_modules\passbook\lib\pass.js:331:3)
    at doneWithImages (...\node_modules\passbook\lib\pass.js:258:12)

**Comment by aishwat** [comment]
+1

**Comment by aishwat** [comment]
For windows, download openssl from http://gnuwin32.sourceforge.net/packages/openssl.htm (Complete package, except sources 'setup file') run that setup.

Now go to installation directory somewhat like `C:\Program Files (x86)\GnuWin32\` go to \bin there u vl find openssl.exe (copy it's path)

Go to computer>properties>advanced system settings>environment variables>system variables choose PATH put path of openssl.exe there

open a cmd type openssl if u get OpenSSL> everything's good

Now re-run ur node code, everything should work
